### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by lzm-bit** [EpsAvlc/livox_simulation#2]
i use gazebo9, when i catkin_make this package have a lot of errors;

error: ‘math’ does not name a type
error: ‘class gazebo::physics::World’ has no member named ‘GetPhysicsEngine’
‘rot_only’ was not declared in this scope
‘offset_rot’ was not declared in this scope

this could gazebo version error, i want to ask your gazebo version.
thank you

**Comment by EpsAvlc** [comment]
Gazebo 7 + Ubuntu 16.04 + ROS kinetic.
Besides, I am sorry that  I don't know the corresponding api in Gazebo 9.
